// This file was autogenerated by app/components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../scripts/app.js', ['sample.config'], ['contacts', 'sample.state']);
goog.addDependency('../../../../scripts/contacts/ContactController.js', ['contacts.ContactController'], []);
goog.addDependency('../../../../scripts/contacts/ContactDetailsItemController.js', ['contacts.ContactDetailsItemController'], ['contacts.state']);
goog.addDependency('../../../../scripts/contacts/ContactDetailsItemEditController.js', ['contacts.ContactDetailsItemEditController'], []);
goog.addDependency('../../../../scripts/contacts/ContactsController.js', ['contacts.ContactsController'], []);
goog.addDependency('../../../../scripts/contacts/module.js', ['contacts', 'contacts.config'], ['contacts.ContactController', 'contacts.ContactDetailsItemController', 'contacts.ContactDetailsItemEditController', 'contacts.ContactsController', 'contacts.services', 'contacts.state']);
goog.addDependency('../../../../scripts/contacts/services/Contact.js', ['contacts.services.ContactFactory'], []);
goog.addDependency('../../../../scripts/contacts/services/module.js', ['contacts.services'], ['contacts.services.ContactFactory']);
goog.addDependency('../../../../scripts/contacts/state.js', ['contacts.state'], []);
goog.addDependency('../../../../scripts/state.js', ['sample.state'], []);
