// This file was autogenerated by app/components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../scripts/app.js', ['sample.config'], ['contacts']);
goog.addDependency('../../../../scripts/contacts/ContactController.js', ['contacts.ContactController'], []);
goog.addDependency('../../../../scripts/contacts/ContactDetailsItemController.js', ['contacts.ContactDetailsItemController'], []);
goog.addDependency('../../../../scripts/contacts/ContactsController.js', ['contacts.ContactsController'], []);
goog.addDependency('../../../../scripts/contacts/module.js', ['contacts'], ['contacts.ContactController', 'contacts.ContactDetailsItemController', 'contacts.ContactsController']);
goog.addDependency('../../../../scripts/services/CityForecast.js', ['WeatherApp.services.CityForecast', 'WeatherApp.services.CityForecastFactory'], []);
goog.addDependency('../../../../scripts/services/WeatherService.js', ['WeatherApp.services.WeatherService', 'WeatherApp.services.WeatherService.cityType'], []);
goog.addDependency('../../../../scripts/services/module.js', ['WeatherApp.services'], ['WeatherApp.services.CityForecastFactory', 'WeatherApp.services.WeatherService']);
